### ISSUE TITLE
illegal read operation error

### ISSUE THREAD

**Issue by jshwlkr** [samrith-s/parcel-plugin-structurize#11]
On Windows, running https://github.com/chrisdmacrae/parceleventy with structurize defaults, and getting this error.

```
(node:24340) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:493:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at allStyles.forEach (D:\Workspace\test\node_modules\parcel-plugin-structurize\src\structurers\assets.structurize.js:35:38)
    at Proxy.forEach (<anonymous>)
    at markups.forEach (D:\Workspace\test\node_modules\parcel-plugin-structurize\src\structurers\assets.structurize.js:27:37)
(node:24340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting
 a promise which was not handled with .catch(). (rejection id: 1)
(node:24340) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with
a non-zero exit code.
```

**Comment by samrith-s** [comment]
Sorry for the delayed response. Hmm.. I will release a fix in some time, wherein it will throw proper errors.

When that's done, it'll be easier to debug what's going wrong. Then, I can help you debug better. :)

**Comment by samrith-s** [comment]
Closing due to inactivity.

**Comment by seamile4kairi** [comment]
Same problem here:

- macOS Mojave
- Node.js v10.16.3
- npm@6.11.2
- parcel-bundler@1.12.3
- parcel-plugin-structurize@1.1.5

**Comment by samrith-s** [comment]
Can you try the newest version? I don’t run into the problem, after this fix.
